# Generated by Django 5.2.6 on 2025-09-24 19:05

import django.db.models.deletion
import django.utils.timezone
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name="Funcionario",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("data_nomeacao", models.DateField(default=django.utils.timezone.now)),
                (
                    "setor",
                    models.CharField(
                        choices=[
                            ("dev", "Desenvolvimento"),
                            ("rh", "Recursos Humanos"),
                            ("financeiro", "Financeiro"),
                            ("comercial", "Comercial"),
                        ],
                        default="dev",
                        max_length=20,
                    ),
                ),
                (
                    "gestor",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="equipe",
                        to="ferias.funcionario",
                    ),
                ),
                (
                    "user",
                    models.OneToOneField(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="funcionario",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
        ),
        migrations.CreateModel(
            name="PeriodoAquisitivo",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("data_inicio", models.DateField()),
                ("data_fim", models.DateField()),
                (
                    "saldo_dias",
                    models.DecimalField(decimal_places=2, default=30.0, max_digits=5),
                ),
                (
                    "funcionario",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="periodos_aquisitivos",
                        to="ferias.funcionario",
                    ),
                ),
            ],
        ),
        migrations.CreateModel(
            name="SolicitacaoFerias",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("data_inicio", models.DateField()),
                ("data_fim", models.DateField()),
                ("data_solicitacao", models.DateTimeField(auto_now_add=True)),
                (
                    "status",
                    models.CharField(
                        choices=[
                            ("pendente", "Pendente"),
                            ("aprovado", "Aprovado"),
                            ("rejeitado", "Rejeitado"),
                        ],
                        default="pendente",
                        max_length=10,
                    ),
                ),
                ("data_aprovacao", models.DateTimeField(blank=True, null=True)),
                ("motivo_rejeicao", models.TextField(blank=True, null=True)),
                ("dias_deduzidos", models.BooleanField(default=False)),
                (
                    "aprovador",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="solicitacoes_aprovadas",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
                (
                    "periodo_aquisitivo",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="solicitacoes_feitas",
                        to="ferias.periodoaquisitivo",
                    ),
                ),
                (
                    "solicitante",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="solicitacoes",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
        ),
    ]
