# Generated by Django 5.2.7 on 2025-11-06 18:24

import django.db.models.deletion
import django.utils.timezone
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='PerfilUsuario',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('matricula', models.CharField(blank=True, max_length=20, null=True, unique=True)),
                ('secretaria', models.CharField(blank=True, max_length=100, null=True)),
                ('cargo', models.CharField(blank=True, max_length=100, null=True)),
                ('data_contratacao', models.DateField(default=django.utils.timezone.now)),
                ('foto_perfil', models.ImageField(blank=True, null=True, upload_to='fotos_perfil/')),
                ('data_nascimento', models.DateField(blank=True, null=True)),
                ('gestor', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='equipe', to='ferias.perfilusuario')),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='perfil', to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='PeriodoAquisitivo',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('data_inicio_aquisitivo', models.DateField()),
                ('data_fim_aquisitivo', models.DateField()),
                ('dias_direito', models.IntegerField(default=30)),
                ('dias_disponiveis', models.IntegerField(default=30)),
                ('status', models.CharField(choices=[('ABERTO', 'Aberto'), ('FECHADO', 'Fechado'), ('VENCIDO', 'Vencido')], default='ABERTO', max_length=20)),
                ('perfil', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='periodos_aquisitivos', to='ferias.perfilusuario')),
            ],
        ),
        migrations.CreateModel(
            name='DescontoFerias',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('dias_descontados', models.IntegerField()),
                ('periodo_aquisitivo', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='ferias.periodoaquisitivo')),
            ],
        ),
        migrations.CreateModel(
            name='SolicitacaoFerias',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('data_inicio', models.DateField()),
                ('data_fim', models.DateField()),
                ('data_solicitacao', models.DateTimeField(auto_now_add=True)),
                ('status', models.CharField(choices=[('PENDENTE_GESTOR', 'Pendente (Gestor)'), ('PENDENTE_RH', 'Pendente (RH)'), ('APROVADA_FINAL', 'Aprovada'), ('REJEITADA', 'Rejeitada')], default='PENDENTE_GESTOR', max_length=20)),
                ('data_aprovacao_gestor', models.DateTimeField(blank=True, null=True)),
                ('data_aprovacao_rh', models.DateTimeField(blank=True, null=True)),
                ('motivo_rejeicao', models.TextField(blank=True, null=True)),
                ('aprovador_gestor', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='ferias_aprovadas_gestor', to=settings.AUTH_USER_MODEL)),
                ('aprovador_rh', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='ferias_aprovadas_rh', to=settings.AUTH_USER_MODEL)),
                ('periodos_utilizados', models.ManyToManyField(related_name='solicitacoes_descontadas', through='ferias.DescontoFerias', to='ferias.periodoaquisitivo')),
                ('solicitante', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='solicitacoes', to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.AddField(
            model_name='descontoferias',
            name='solicitacao',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='ferias.solicitacaoferias'),
        ),
        migrations.AlterUniqueTogether(
            name='descontoferias',
            unique_together={('solicitacao', 'periodo_aquisitivo')},
        ),
    ]
