# Generated by Django 5.2.7 on 2025-11-07 15:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ferias', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='solicitacaoferias',
            name='status',
            field=models.CharField(choices=[('PENDENTE_GESTOR', 'Pendente (Gestor)'), ('APROVADA_FINAL', 'Aprovada'), ('REJEITADA', 'Rejeitada')], default='PENDENTE_GESTOR', max_length=20),
        ),
    ]
