# Generated by Django 5.2.7 on 2025-11-11 14:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ferias', '0002_alter_solicitacaoferias_status'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='solicitacaoferias',
            name='aprovador_rh',
        ),
        migrations.RemoveField(
            model_name='solicitacaoferias',
            name='data_aprovacao_rh',
        ),
        migrations.AddField(
            model_name='perfilusuario',
            name='lotacao',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='perfilusuario',
            name='onboarding_completo',
            field=models.BooleanField(default=False),
        ),
    ]
